name: test
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
        - 25.3
        - 26.3
        - 27.1
        - snapshot
    env:
      EMACS_VERSION: ${{ matrix.emacs_version }}
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: conao3/setup-cask@master
    - uses: actions/checkout@v2
    - name: Test
      run: |
        cask install
        cask exec ert-runner
    - uses: codecov/codecov-action@v1
      with:
        env_vars: EMACS_VERSION
